name = "ee-tracker"
main = "src/index.js"
compatibility_date = "2024-06-01"

[[d1_databases]]
binding = "DB"
database_name = "ee-tracker-db"
database_id = "ddc0f2a4-8cc9-4ad8-b6fe-1219dae88aea"

[[kv_namespaces]]
binding = "STATIC"
id = "4f1bfe27cd80437d974e36ddee082089"

[observability.logs]
enabled = true
