name = "ee-tracker"
main = "src/index.js"
compatibility_date = "2024-06-01"

[[d1_databases]]
binding = "DB"
database_name = "ee-tracker-db"
database_id = "9a8252de-fdce-4c7e-9109-7c6307060c13"

[site]
bucket = "./public"
include = ["index.html", "app.js"]

[observability.logs]
enabled = true
